name: Configurar VM Magalu Cloud

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  setup-vm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Testar Conexão SSH
        run: |
          echo "${{ secrets.ID_ED25519_MESSIAS }}" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@201.54.11.116 "echo 'Conexão SSH bem-sucedida!'"

