name: Configurar Cluster PostgreSQL

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  setup-vms:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host: [201.54.11.116, 201.54.11.119, 201.54.11.120, 201.54.11.121, 201.54.11.122]  # Lista de VMs

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Cluster PostgreSQL
        run: |
          echo "${{ secrets.ID_ED25519 }}" | tr -d '\r' > private_key.pem
          chmod 600 private_key.pem

          ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@${{ matrix.host }} << 'EOF'
            echo "🚀 Iniciando configuração em $HOSTNAME"

            # Configurar /etc/hosts
            echo -e "201.54.11.116  pgha1\n201.54.11.119  pgha2\n201.54.11.120  pgha3\n201.54.11.121  pghaproxy\n201.54.11.122  pghaproxy2" | sudo tee -a /etc/hosts

            # Desativar SELinux e firewall
            sudo sed -i "s/SELINUX=enforcing/SELINUX=disabled/" /etc/selinux/config
            sudo setenforce 0
            sudo systemctl disable --now firewalld.service
            sudo reboot

            # Instalar PostgreSQL e TimescaleDB
            sudo dnf install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm
            sudo dnf install -y postgresql16-server postgresql16
            sudo ln -s /usr/pgsql-16/bin/* /usr/sbin/

            # Configurar diretórios
            sudo mkdir -p /usr/local/pgsql
            sudo chown postgres:postgres /usr/local/pgsql
            sudo chmod 0750 -R /usr/local/pgsql
            sudo rm -rf /var/lib/pgsql/16/data
            sudo ln -s /usr/local/pgsql/data/ /var/lib/pgsql/16/

            # Desativar serviço PostgreSQL (será iniciado manualmente depois)
            sudo systemctl disable --now postgresql-16.service

            # Instalar TimescaleDB
            echo -e "[timescale_timescaledb]\nname=timescale_timescaledb\nbaseurl=https://packagecloud.io/timescale/timescaledb/el/\$(rpm -E %{rhel})/\$basearch\nrepo_gpgcheck=1\ngpgcheck=0\nenabled=1\ngpgkey=https://packagecloud.io/timescale/timescaledb/gpgkey\nsslverify=1\nsslcacert=/etc/pki/tls/certs/ca-bundle.crt\nmetadata_expire=300" | sudo tee /etc/yum.repos.d/timescale_timescaledb.repo
            sudo dnf -y install timescaledb-2-postgresql-16

            echo "✅ Configuração finalizada com sucesso!"
          EOF

