name: Configurar DB Postgresql na Magalu Cloud

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-vm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Banco Postgres na Magalu Cloud
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 201.54.2.74
          username: ubuntu
          key: "${{ secrets.ID_ED25519 }}"
          script: |
             echo "Conexão SSH bem-sucedida!"
